# environment variables
variable "project_name" {}
variable "environment" {}
# vpc variables
variable "private_app_subnet_az1_id" {}
variable "private_app_subnet_az2_id" {}
# rds variables
variable "db_snapshot_identifier" {}
variable "db_instance_class" {}
variable "availability_zone_2" {}
variable "db_instance_identifier" {}
variable "db_snapshot_identifier" {}
variable "multi_az_deployment" {}
variable "database_security_group_id" {}
